### ISSUE TITLE
About paper

### ISSUE THREAD

**Issue by youralan** [nuriyeyldrm/deep_image_fusion#1]
Hello,do you have a blog or paper corresponding to the code?  thanks.

**Comment by nuriyeyldrm** [comment]
Hello, yes, I have a report for the python part. I can share it if you want. But the MATLAB algorithm works differently, and I added it later. I don't have a document for it yet. I plan to write soon. Thank you for your interest.

**Comment by youralan** [comment]
Thank you very much, i need your python document to understand the code. This is my email 1153665882@qq.com.

**Comment by nuriyeyldrm** [comment]
You're welcome, I have sent the document.
